### ISSUE TITLE
缺少opencv2文件夹

### ISSUE THREAD

**Issue by LinChiSin** [lililqth/ParticleFilter#1]
你好，在您的ParticalFilter.cpp文件中使用了如下语句：
`#include <opencv2/opencv.hpp>`
但在文件夹中却并没有包含。

**Comment by lililqth** [comment]
您好！该文件夹是 opencv 所提供的，请首先配置 opencv~
由于该项目时间久远，可能当前的路径有所变化，请先跑通 opencv 提供的 Demo。
